name: lstmstockproject
channels:
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
dependencies:
  - python=3.11
  - numpy
  - ipykernel
  - matplotlib
  - pandas
  - seaborn
prefix: /Users/ryandang/miniconda3/envs/lstmstockproject
